# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0buserservice\"\"\n\x11\x45mailDaVerificare\x12\r\n\x05\x65mail\x18\x01 \x01(\t\".\n\rEsitoVerifica\x12\x0e\n\x06\x65siste\x18\x01 \x01(\x08\x12\r\n\x05\x65sito\x18\x02 \x01(\t2Z\n\x0bUserService\x12K\n\rVerificaEmail\x12\x1e.userservice.EmailDaVerificare\x1a\x1a.userservice.EsitoVerificab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMAILDAVERIFICARE']._serialized_start=35
  _globals['_EMAILDAVERIFICARE']._serialized_end=69
  _globals['_ESITOVERIFICA']._serialized_start=71
  _globals['_ESITOVERIFICA']._serialized_end=117
  _globals['_USERSERVICE']._serialized_start=119
  _globals['_USERSERVICE']._serialized_end=209
# @@protoc_insertion_point(module_scope)
