### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
#http### Test 1: Registra utente con ID casuale (mario.rossi)
#Utente registrato correttamente
POST http://127.0.0.1:5001/register
Content-Type: application/json

{
  "id": "{{$uuid}}",
  "email": "Mario.rossi@email.it",
  "name": "Mario",
  "surname": "Rossi"
}

###

### Test 2: Registra stesso utente con ID diverso (test duplicato email)
#Utente già registrato
POST http://127.0.0.1:5001/register
Content-Type: application/json

{
  "id": "{{$uuid}}",
  "email": "Mario.rossi@email.it",
  "name": "Mario",
  "surname": "Rossi"
}

###

### Test 3: Registra utente con ID fisso (Mario.Rossi)

POST http://127.0.0.1:5001/register
Content-Type: application/json

{
  "id": "e547e941-8a22-4d53-a408-487a67ee10d1",
  "email": "Mario.rossi@email.it",
  "name": "Mario",
  "surname": "Rossi"
}

###

### Test 4: Elimina utente

DELETE http://127.0.0.1:5001/delete
Content-Type: application/json

{
  "email": "Mario.rossi@email.it"
}

###

### Test 5: SottoscriviIntersse utente non presente (GRPC)

POST http://localhost:5002/subscribeInterest
Content-Type: application/json

{
    "email": "angelo.macchiavelli@email.it",
    "interessi": ["LIRF", "EDDF","LSZH","LSGG","EDDM"]
}

###

### Test 6: SottoscriviInterssi (Utente registrato) "LIRF","EDDF","LSZH","LSGG","EDDM","LIML","LIMC","LIME"]

POST http://localhost:5002/subscribeInterest
Content-Type: application/json

{
  "email": "Mario.rossi@email.it",
  "interessi": ["LSZH","EDDM"]
}


###

## Test 7: Elimina Interesse

DELETE http://localhost:5002/removeInterest
Content-Type: application/json

{
    "email": "Mario.rossi@email.it",
    "interessi": ["OMDB","KATL","LIRF","EDDF","LSZH","LSGG","EDDM","LIML","LIMC","LIME"]
}

###

## TEST 8 Ottieni informazioni aereporto
GET http://localhost:5002/flights/info?icao=LSZH
email: Mario.rossi@email.it
Accept: application/json

###
## TEST 9 ultimo arrivo/partenza
GET http://localhost:5002/flights/last?airport=LSZH&type=arrival
email: Mario.rossi@email.it
Accept: application/json

###
GET http://localhost:5002/flights/last?airport=LSZH&type=departure
email: Mario.rossi@email.it
Accept: application/json

###
# TEST 10 Media partenze/arrivi
GET http://localhost:5002/flights/average?airport=LSZH&days=5&type=departure
email: Mario.rossi@email.it
Accept: application/json

###
GET http://localhost:5002/flights/average?airport=LSZH&days=1&type=arrival
email: Mario.rossi@email.it
Accept: application/json