kind: Secret
apiVersion: v1
metadata:
  name: app-secrets
  namespace: flights-monitoring
type: Opaque
stringData:
  # DB pass
  mysql-root-password: root

  # OpenSky
  opensky-client-id: ID_SECRET_OPENSKY
  opensky-client-secret: CLIENT_SECRET_OPENSKY

  # Gmail
  gmail-user: USER_AUTH_EMAIL
  gmail-password: "USER_AUTH_SECRET"