# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0cuser_service\"\x1c\n\x0bUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\x1e\n\x0cUserResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\"\"\n\x0f\x44\x65letedResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32R\n\x0bUserService\x12\x43\n\nVerifyUser\x12\x19.user_service.UserRequest\x1a\x1a.user_service.UserResponse2b\n\x14\x44\x61taCollectorService\x12J\n\x0eremoveInterest\x12\x19.user_service.UserRequest\x1a\x1d.user_service.DeletedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=36
  _globals['_USERREQUEST']._serialized_end=64
  _globals['_USERRESPONSE']._serialized_start=66
  _globals['_USERRESPONSE']._serialized_end=96
  _globals['_DELETEDRESPONSE']._serialized_start=98
  _globals['_DELETEDRESPONSE']._serialized_end=132
  _globals['_USERSERVICE']._serialized_start=134
  _globals['_USERSERVICE']._serialized_end=216
  _globals['_DATACOLLECTORSERVICE']._serialized_start=218
  _globals['_DATACOLLECTORSERVICE']._serialized_end=316
# @@protoc_insertion_point(module_scope)
